#!/usr/bin/env python

import argparse, logging
# import guestfs

class Configurator:
    def __init__(self):
        self.log = logging.getLogger(__name__)
        self.log.setLevel(logging.DEBUG)
        self.log.addHandler(logging.StreamHandler())

        self.parser = argparse.ArgumentParser(description='Alter GRUB2 options inside virtual machine image')
        self.parser.add_argument('disk_image', help='Name of disk image file to alter')
        self.parser.add_argument('-t', '--timeout', type=int, help='Set boot timeout in seconds,' \
                ' in case of VMs it\'s handy to set it to 0')
        self.parser.add_argument('-g', '--gfx-mode', help='GFX_MODE for the console, e.g.' \
                ' \'1024x768\' or \'800x600\' (without quotes)')

        self.args = self.parser.parse_args()

        self.log.debug('[%s] parsed command line arguments %s', self.__class__.__name__, self.args)

config = Configurator()
