#!/usr/bin/env python3

from vm_common import GuestFSDisk
from cmdline import Command
from os.path import basename, join

class SetRepo(Command):
    def __init__(self):
        super(SetRepo, self).__init__('Set the baseurl variable in CentOS-Base.repo,' \
                ' useful if you have created a local package cache')

        self.add_argument('repo_url', help='new value of \'baseurl\' variable')
        self.add_argument('disk_image', help='name of disk image to alter')
        
        self.parse_args()
        self.disk_image = self.args.disk_image
        self.repo_url = self.args.repo_url

def set_repository_baseurl(disk, url, log):
    reponames = {
            'base' : 'os',
            'updates' : 'updates',
            'extras' : 'extras',
            'centosplus' : 'centosplus',
            'contrib' : 'contrib',
    }

    paths = disk.gfs.aug_match('/files/etc/yum.repos.d/CentOS-Base.repo/*[label() != \'#comment\']')
    print(paths)
    repos = [(join(path,'baseurl'), reponames[basename(path)])
            for path in paths]

    url_template = '{url}/centos/$releasever/{repo}/$basearch/'

    # add baseurl variable
    for path, repo in repos:
        disk.gfs.aug_set(path, url_template.format(url=url, repo=repo))

    # remove mirrorlist variable
    for path in paths:
        disk.gfs.aug_rm(join(path,'mirrorlist'))

    disk.gfs.aug_save()

def set_epel_repository_baseurl(disk, url, log):
    reponames = {
            'epel'              : '$basearch',
            'epel-debuginfo'    : '$basearch/debug',
            'epel-source'       : 'SRPMS',
    }

    if (disk.gfs.is_file("/etc/yum.repos.d/epel.repo")):
        paths = disk.gfs.aug_match('/files/etc/yum.repos.d/epel.repo/*[label() != \'#comment\']')
        repos = [(join(path,'baseurl'), reponames[basename(path)])
                for path in paths]

        url_template = '{url}/fedora/epel/7/{repo}'

        # add baseurl variable
        for path, repo in repos:
            disk.gfs.aug_set(path, url_template.format(url=url, repo=repo))

        # remove mirrorlist variable
        for path in paths:
            disk.gfs.aug_rm(join(path,'mirrorlist'))

        disk.gfs.aug_save()
    else:
        self.info("EPEL repository is not enabled on guest")

cmd = SetRepo()

disk = GuestFSDisk(cmd.disk_image, cmd.log)

set_repository_baseurl(disk, cmd.repo_url, cmd.log)
set_epel_repository_baseurl(disk, cmd.repo_url, cmd.log)
