#!/usr/bin/env python2

import argparse, logging
import os, os.path
import csv, io
from collections import namedtuple

import guestfs

loglevel = 'warn'
loglevels = { 'debug' : logging.DEBUG,
              'info' : logging.INFO,
              'warn' : logging.WARNING}

class ParseLoglevel(argparse.Action):
    def __init__(self, option_strings, dest, nargs=None, **kwargs):
        if nargs is not None:
            raise ValueError("nargs not allowed")
        super(ParseLoglevel, self).__init__(option_strings, dest, **kwargs)
    def __call__(self, parser, namespace, values, option_string=None):
        loglevel = self.parse_loglevel(values)
        setattr(namespace, self.dest, loglevel)
    def parse_loglevel(self, loglevel_string):
        try:
            return loglevels[loglevel_string]
        except:
            msg = '{} is not a supported loglevel'.format(loglevel_string)
            raise argparse.ArgumentTypeError(msg)

User = namedtuple('User', ['uid','gid','home'])
def parse_etc_passwd(file_contents):
    mem_file = io.BytesIO(file_contents)
    passwdreader = csv.reader(mem_file, delimiter=':')
    users = {}
    for row in passwdreader:
        username = row[0]
        uid = int(row[2])
        gid = int(row[3])
        home = row[5]
        if uid >= 1000:
            users[username] = User(uid=uid, gid=gid, home=home)
    return users

parser = argparse.ArgumentParser(description='Add your SSH public keys to a user on a virtual machine disk')
parser.add_argument('image', metavar='DISK_IMAGE', type=str, help='name of the target disk image')
parser.add_argument('-l','--loglevel', help='log message verbosity', default=logging.WARNING, choices=loglevels, action=ParseLoglevel)

args = parser.parse_args()

cwd = os.getcwd()
log = logging.getLogger(__name__)
log.addHandler(logging.StreamHandler())
log.setLevel(args.loglevel)
log.debug('cwd %s', cwd)

image_path = os.path.normpath(os.path.join(cwd,args.image))
if not os.path.isfile(image_path):
    log.error('Image %s does not exists, is not accessible or not a regular file', image_path)
    exit(1)

log.info('Modifying image %s', image_path)

gfs = guestfs.GuestFS(python_return_dict=True)

gfs.add_drive(args.image)
gfs.launch()
gfs.mount("/dev/sda2","/")

etc_passwd = gfs.cat('/etc/passwd')
users = parse_etc_passwd(etc_passwd)
print(users)
